language: python

matrix:
  include:
    - python: 2.7
      dist: xenial
      sudo: true
    - python: 3.6
      dist: xenial
      sudo: true
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install tox-travis coveralls

script:
  - tox

after_success:
  - coveralls
